using System.Text.Json.Serialization;
using Plex.MCP.Host.Models.Output;

namespace Plex.MCP.Host.Models.PlexApi;

public record PlexMediaItem(
    [property: JsonPropertyName("ratingKey")] string RatingKey,
    [property: JsonPropertyName("key")] string Key,
    [property: JsonPropertyName("parentRatingKey")] string? ParentRatingKey,
    [property: JsonPropertyName("grandparentRatingKey")] string? GrandparentRatingKey,
    [property: JsonPropertyName("parentGuid")] string? ParentGuid,
    [property: JsonPropertyName("grandparentGuid")] string? GrandparentGuid,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("parentTitle")] string? ParentTitle,
    [property: JsonPropertyName("grandparentTitle")] string? GrandparentTitle,
    [property: JsonPropertyName("titleSort")] string? TitleSort,
    [property: JsonPropertyName("summary")] string? Summary,
    [property: JsonPropertyName("index")] int? Index,
    [property: JsonPropertyName("parentIndex")] int? ParentIndex,
    [property: JsonPropertyName("rating")] float? Rating,
    [property: JsonPropertyName("year")] int? Year,
    [property: JsonPropertyName("thumb")] string? Thumb,
    [property: JsonPropertyName("art")] string? Art,
    [property: JsonPropertyName("parentThumb")] string? ParentThumb,
    [property: JsonPropertyName("grandparentThumb")] string? GrandparentThumb,
    [property: JsonPropertyName("grandparentArt")] string? GrandparentArt,
    [property: JsonPropertyName("duration")] long? Duration,
    [property: JsonPropertyName("originallyAvailableAt")] string? OriginallyAvailableAt,
    [property: JsonPropertyName("addedAt")] long AddedAt,
    [property: JsonPropertyName("updatedAt")] long UpdatedAt,
    [property: JsonPropertyName("audienceRating")] float? AudienceRating,
    [property: JsonPropertyName("audienceRatingImage")] string? AudienceRatingImage,
    [property: JsonPropertyName("chapterSource")] string? ChapterSource,
    [property: JsonPropertyName("contentRating")] string? ContentRating,
    [property: JsonPropertyName("ratingImage")] string? RatingImage,
    [property: JsonPropertyName("studio")] string? Studio,
    [property: JsonPropertyName("tagline")] string? Tagline,
    [property: JsonPropertyName("viewCount")] int? ViewCount,
    [property: JsonPropertyName("skipCount")] int? SkipCount,
    [property: JsonPropertyName("lastViewedAt")] long? LastViewedAt,
    [property: JsonPropertyName("librarySectionTitle")] string? LibrarySectionTitle,
    [property: JsonPropertyName("librarySectionID")] int? LibrarySectionId,
    [property: JsonPropertyName("librarySectionKey")] string? LibrarySectionKey,
    [property: JsonPropertyName("playlistType")] string? PlaylistType,
    [property: JsonPropertyName("composite")] string? Composite,
    [property: JsonPropertyName("leafCount")] int? LeafCount,
    [property: JsonPropertyName("childCount")] int? ChildCount,
    [property: JsonPropertyName("skipChildren")] bool? SkipChildren,
    [property: JsonPropertyName("Genre")] List<PlexGenre>? Genres = null,
    [property: JsonPropertyName("Country")] List<PlexCountry>? Countries = null,
    [property: JsonPropertyName("Director")] List<PlexDirector>? Directors = null,
    [property: JsonPropertyName("Writer")] List<PlexWriter>? Writers = null,
    [property: JsonPropertyName("Producer")] List<PlexProducer>? Producers = null,
    [property: JsonPropertyName("Role")] List<PlexRole>? Roles = null,
    [property: JsonPropertyName("Similar")] List<PlexSimilar>? Similar = null,
    [property: JsonPropertyName("Collection")] List<PlexCollection>? Collections = null,
    [property: JsonPropertyName("Label")] List<PlexLabel>? Labels = null,
    [property: JsonPropertyName("Media")] List<PlexMedia>? Media = null,
    [property: JsonPropertyName("guid")] string? GuidString = null,
    [property: JsonPropertyName("Guid")] List<PlexGuidItem>? ExternalGuids = null
);